/**
 * BlockDAG Smart Contract Deployment Script
 * 
 * This script can be run directly in BlockDAG IDE to compile and deploy
 * the HealthPassport smart contract.
 * 
 * Instructions:
 * 1. Copy the entire HealthPassport.sol contract code
 * 2. Paste this script into BlockDAG IDE
 * 3. Update the RPC_URL and PRIVATE_KEY variables
 * 4. Run the script to deploy
 * 5. Download the generated ABI file
 * 6. Save the ABI to your codebase at: contracts/HealthPassport.json
 */

const Web3 = require('web3');

// ==================== CONFIGURATION ====================
// Update these values for your deployment
const RPC_URL = 'https://api.testnet.blockdag.network'; // BlockDAG Testnet RPC URL
const PRIVATE_KEY = 'YOUR_PRIVATE_KEY_HERE'; // Your wallet private key (keep secure!)
const GAS_LIMIT = 5000000; // Gas limit for deployment
const GAS_PRICE = '20000000000'; // 20 Gwei

// ==================== CONTRACT CODE ====================
// Paste your compiled contract bytecode here
// This will be generated by the BlockDAG IDE compiler
const CONTRACT_BYTECODE = ''; // Will be filled by BlockDAG IDE

// ==================== CONTRACT ABI ====================
// This will be generated by the BlockDAG IDE compiler
const CONTRACT_ABI = []; // Will be filled by BlockDAG IDE

// ==================== DEPLOYMENT SCRIPT ====================
async function deployHealthPassport() {
  try {
    console.log('🚀 Starting HealthPassport deployment to BlockDAG...\n');

    // Initialize Web3
    const web3 = new Web3(new Web3.providers.HttpProvider(RPC_URL));
    
    // Add account from private key
    const account = web3.eth.accounts.privateKeyToAccount(PRIVATE_KEY);
    web3.eth.accounts.wallet.add(account);
    web3.eth.defaultAccount = account.address;

    console.log('📝 Deployer Address:', account.address);
    
    // Check balance
    const balance = await web3.eth.getBalance(account.address);
    console.log('💰 Balance:', web3.utils.fromWei(balance, 'ether'), 'BDAG\n');

    if (balance === '0') {
      throw new Error('Insufficient balance. Please fund your account first.');
    }

    // Get current gas price
    const currentGasPrice = await web3.eth.getGasPrice();
    console.log('⛽ Current Gas Price:', web3.utils.fromWei(currentGasPrice, 'gwei'), 'Gwei');

    // Create contract instance
    const contract = new web3.eth.Contract(CONTRACT_ABI);

    console.log('\n📦 Deploying contract...');

    // Deploy contract
    const deployTx = contract.deploy({
      data: CONTRACT_BYTECODE,
      arguments: [] // Constructor arguments (none for HealthPassport)
    });

    // Estimate gas
    const estimatedGas = await deployTx.estimateGas({ from: account.address });
    console.log('⛽ Estimated Gas:', estimatedGas);

    // Send transaction
    const deployedContract = await deployTx.send({
      from: account.address,
      gas: GAS_LIMIT,
      gasPrice: GAS_PRICE
    });

    console.log('\n✅ Contract deployed successfully!');
    console.log('📍 Contract Address:', deployedContract.options.address);
    console.log('🔗 Transaction Hash:', deployedContract.transactionHash);

    // Save deployment info
    const deploymentInfo = {
      contractAddress: deployedContract.options.address,
      transactionHash: deployedContract.transactionHash,
      deployer: account.address,
      timestamp: new Date().toISOString(),
      network: 'BlockDAG Testnet',
      abi: CONTRACT_ABI
    };

    console.log('\n📄 Deployment Information:');
    console.log(JSON.stringify(deploymentInfo, null, 2));

    console.log('\n🎉 Deployment Complete!');
    console.log('\n📋 Next Steps:');
    console.log('1. Save the contract address:', deployedContract.options.address);
    console.log('2. Download the ABI from BlockDAG IDE');
    console.log('3. Update your frontend code with the contract address');
    console.log('4. Save the ABI to: contracts/HealthPassport.json');

    return deploymentInfo;

  } catch (error) {
    console.error('❌ Deployment failed:', error.message);
    if (error.stack) {
      console.error('\nStack trace:', error.stack);
    }
    throw error;
  }
}

// Run deployment
deployHealthPassport()
  .then((info) => {
    console.log('\n✅ Script completed successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Script failed:', error);
    process.exit(1);
  });

// Export for use as module
module.exports = { deployHealthPassport };
